_wandb:
    value:
        cli_version: 0.22.2
        e:
            1qkfaxkd6yc182iymage909pyjg25kcu:
                codePath: class/week 10/wandb_cloud_deploy_lab_detailed.ipynb
                codePathLocal: wandb_cloud_deploy_lab_detailed.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "102611623936"
                        used: "36395663360"
                email: 142502006@smail.iitpkd.ac.in
                executable: /usr/bin/python3
                git:
                    commit: 3d5e44955ac42020a9bb54faf8f5b73fb266d196
                    remote: https://github.com/Aryan123661/mlops2025w_142502006.git
                host: aryan
                memory:
                    total: "14506876928"
                os: Linux-6.8.0-85-generic-x86_64-with-glibc2.35
                program: wandb_cloud_deploy_lab_detailed.ipynb
                python: CPython 3.10.12
                root: /media/aryan/Storage/mlops2025w_142502006/class/week 10
                startedAt: "2025-10-14T04:22:42.509646Z"
                writerId: 1qkfaxkd6yc182iymage909pyjg25kcu
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
            "4": 3.10.12
            "5": 0.22.2
            "8":
                - 1
            "12": 0.22.2
            "13": linux-x86_64
